# Generated by Django 3.2 on 2021-04-09 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
        migrations.AlterField(
            model_name='note',
            name='task_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 18, 2, 28, 880769, tzinfo=utc)),
        ),
    ]
